/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {

  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [
    // {
    //   type: 'link',
    //   label: 'Documentation', // The link label
    //   href: '/', // The internal path
    // },
    {
      type: 'autogenerated', dirName: '.',

    }
],

};

module.exports = sidebars;
