name: Check Python package version numbers

on:
  pull_request:
    paths:
      - '**/pyproject.toml'
      - 'packages/**/__about__.py'

permissions:
  id-token: write
  contents: read

jobs:
  check:
    uses: ./.github/workflows/reusable-check-python-package-versions.yaml
    with:
      before_commit: ${{ github.event.pull_request.base.sha }}
      after_commit: ${{ github.event.pull_request.head.sha }}
