name: Change Type label verification

on:
  pull_request:
    types: [opened, edited, labeled, unlabeled, synchronize]

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  check-label:
    name: Check label
    runs-on: ubuntu-latest

    permissions:
      contents: read # Required for reading PR labels

    steps:
      - name: Require exactly one change type label
        uses: actions/github-script@ed597411d8f924073f98dfc5c65a23a2325f34cd # v8
        with:
          script: |
            const allChangeTypeLabels = new Set([
              'change type - cosmetic 🌹',
              'change type - documentation - docs team 📝',
              'change type - documentation - member 📝',
              'change type - major 🚨',
              'change type - minor 🤏',
              'automation 🦾',
            ]);
            const prLabels = context.payload.pull_request.labels.map(label => label.name);
            const appliedChangeTypeLabels = prLabels.filter(prLabel => allChangeTypeLabels.has(prLabel));
            if (appliedChangeTypeLabels.length !== 1) {
              const baseMessage = `The PR must have EXACTLY one of the following CHANGE TYPE labels: ${Array.from(allChangeTypeLabels).sort().join(', ')}. `
              const n = appliedChangeTypeLabels.length;
              let contextualMessage;
              if (n === 0) {
                contextualMessage = 'It currently has no change type label. Please ➕ add one label. 🙏'
              } else {
                contextualMessage = `It currently has ${n} change type labels (${JSON.stringify(appliedChangeTypeLabels)}). 🙏 Please ❌ remove ${n-1} label(s).`
              }
              core.setFailed(baseMessage + contextualMessage);
            }
