name: Check Pydantic models

on:
  pull_request_target:
    paths:
      - 'packages/**'
      - 'pyproject.toml'
      - 'uv.lock'

jobs:
  check:
    runs-on: ubuntu-latest
    if: github.event.pull_request.head.repo.full_name == github.repository

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          version: "latest"

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: uv sync

      - name: Run make check
        run: make check
