---
name: Publish the `schema` folder to schema.overturemaps.org

on:
  push:
    branches: [main]

  # Allow running from the actions tab
  workflow_dispatch:

permissions:
  contents: write

jobs:
  publish:
    if: github.repository == 'overturemaps/schema'
    runs-on: ubuntu-latest
    steps:
      - name: Check out the schema repository
        uses: actions/checkout@v3

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: schema
