# This is based on the Go starter workflow from:
# https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Validate schema, examples, and counterexamples

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: 1.22
    - name: Install dependencies
      run: go install github.com/santhosh-tekuri/jsonschema/cmd/jv@latest
    - name: Validate
      run: ./test.sh
