name: Publish Python packages to PyPI

on:
  push:
    branches: [main, pypi-auto-publish-gh-action]
    paths:
      - '**/pyproject.toml'
      - 'packages/**/__about__.py'

permissions:
  id-token: write
  contents: read

jobs:
  check:
    if: github.event.repository.full_name == github.repository
    uses: ./.github/workflows/reusable-check-python-package-versions.yaml
    with:
      before_commit: ${{ github.event.before }}
      after_commit: ${{ github.event.after }}

  get-index-url:
    uses: ./.github/workflows/reusable-get-code-artifact-index-url.yaml
    with:
      role_name: GithubActions_Schema_CodeArtifact_Publish

  publish:
    needs: [check, get-index-url]
    if: github.event.pull_request.head.repo.full_name == github.repository
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package: ${{ fromJson(needs.check.outputs.changed_packages) }}
    steps:
      - name: Publish changed packages to PyPI
        run: |
          package="${{ matrix.package }}"
          before="${{ matrix.before }}"
          after="${{ matrix.after }}"
          printf 'Publishing package %s version %s to PyPI (previous version %s)...' "$package" "$before" "$after"
          uv build --package "$package"
          wheel="dist/${package//-/_}-${after}-py3-none-any.whl"
          if [ ! -f "$wheel" ]; then
            echo "    Wheel file [$wheel] not found. Aborting!"
            exit 1
          fi
          tarball="dist/${package//-/_}-${after}.tar.gz"
          if [ ! -f "$tarball" ]; then
            echo "    Source tarball file [$tarball] not found. Aborting!"
            exit 1
          fi
          uv publish "$wheel" "$tarball" --publish-url "${{ needs.get-index-url.outputs.index_url }}"
