name: "[REUSABLE] Get CodeArtifact Python package index URL"

on:
  workflow_call:
    inputs:
      account_id:
        description: The AWS account ID that owns the CodeArtifact domain
        type: string
        required: false
        default: 505071440022
      aws_region:
        description: The AWS region where the CodeArtifact repository is hosted
        type: string
        required: false
        default: us-west-2
      role_name:
        description: The name of the IAM role to assume for accessing CodeArtifact
        type: string
        required: false
        default: GithubActions_Schema_CodeArtifact_ReadOnly
      domain:
        description: The CodeArtifact domain name
        type: string
        required: false
        default: overture-pypi
      repository:
        description: The CodeArtifact repository name
        type: string
        required: false
        default: overture
    outputs:
      index_url:
        description: The CodeArtifact Python index URL
        value: ${{ jobs.get-code-artifact-index-url.outputs.index_url }}

jobs:
  get-code-artifact-index-url:
    runs-on: ubuntu-latest
    outputs:
      index_url: ${{ steps.get-code-artifact-index-url.outputs.index_url }}
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ inputs.aws_region }}
          role-to-assume: arn:aws:iam::${{ inputs.account_id }}:role/${{ inputs.role_name }}
          role-session-name: GitHubActions_${{github.job}}_${{github.run_id}}

      - name: Get CodeArtifact index URL
        id: get-code-artifact-index-url
        run: |
          AUTH_TOKEN=$(aws codeartifact get-authorization-token \
            --domain ${{ inputs.domain }} \
            --domain-owner ${{ inputs.account_id }} \
            --query authorizationToken \
            --output text)
          echo "index_url=https://aws:${AUTH_TOKEN}@$${{ inputs.domain }}-${{ inputs.account_id }}.d.codeartifact.${{ inputs.aws_region }}.amazonaws.com/" >> $GITHUB_OUTPUT
